export const USER_TYPES = {
    GUEST : 'guest',
    USER : 'user'
}

export const ALLOWED_COUNTRIES = [
    "Austria", 
    "Belgium", 
    "Bulgaria", 
    "Croatia", 
    "Canada",
    "Cyprus", 
    "Czech Republic", 
    "Denmark", 
    "Estonia", 
    "Finland", 
    "France", 
    "Germany", 
    "Greece", 
    "Hungary", 
    "Ireland", 
    "Italy", 
    "Latvia", 
    "Lithuania", 
    "Luxembourg", 
    "Malta", 
    "Netherlands", 
    "Poland", 
    "Portugal", 
    "Romania", 
    "Slovakia", 
    "Slovenia",
    "Saudi Arabia",
    "Spain", 
    "Sweden",
    "United Arab Emirates",
    "UK",
    "USA",
]