export const USER_TYPES = {
    GUEST : 'guest',
    USER : 'user'
}

// export const RESTRICTED_COUNTRIES = ['PK', 'IN', 'CN', 'BD'];
export const RESTRICTED_COUNTRIES = ['PK', 'IN', 'CN', 'BD'];

export const ORDER_STATUS = {
    PAYMENT_PENDING : 'Payment Pending',
    IN_PROCESS : 'In Process',
    SHIPPED : 'Shipped',
    CANCELLED : 'Cancelled',
}

export const COUNTRY_CODES = [
    "+1",
    "+92",
    "+44",
    "+355",
    "+213",
    "+54",
    "+374",
    "+61",
    "+994",
    "+973",
    "+357",
    "+358",
    "+55",
    "+49",
    "+233",
    "+30",
    "+299",
    "+852",
    "+39",
    "+64",
    "+48",
    "+974",
    "+40",
    "+7",
    "+250",
    "+65",
    "+34",
    "+268",
    "+46",
    "+886",
    "+66",
    "+971",
    "+966"
];

export const ALLOWED_COUNTRIES = [
    "Austria",
    "Azerbaijan",
    "Bahrain", 
    "Belgium", 
    "Croatia", 
    "Canada",
    "Cyprus", 
    "Czech Republic", 
    "Denmark", 
    "Estonia", 
    "Finland", 
    "France", 
    "Germany", 
    "Greece", 
    "Hungary", 
    "Ireland", 
    "Italy", 
    "Latvia", 
    "Lithuania", 
    "Luxembourg", 
    "Malta", 
    "Netherlands",
    "Pakistan", 
    "Poland", 
    "Portugal", 
    "Romania", 
    "Slovakia", 
    "Slovenia",
    "Saudi Arabia",
    "Spain", 
    "Sweden",
    "United Arab Emirates",
    "UK",
    "USA",
]